### ISSUE TITLE
print 'Error: Sentry requires Python 2.7'

### ISSUE THREAD

**Issue by bashu** [darklow/dokku-sentry#6]
```
       Collecting cffi==1.5.0 (from -r /tmp/build/requirements.txt (line 1))
       Downloading cffi-1.5.0.tar.gz (385kB)
       Collecting sentry==8.0.5 (from -r /tmp/build/requirements.txt (line 2))
       Downloading sentry-8.0.5.tar.gz (6.5MB)
       Complete output from command python setup.py egg_info:
       Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-7a0japsu/sentry/setup.py", line 30
       print 'Error: Sentry requires Python 2.7'
       ^
       SyntaxError: Missing parentheses in call to 'print'

----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7a0japsu/sentry/
```

**Comment by mimischi** [comment]
Hey @bashu. I'm not sure if this repository is maintained anymore. That's why I've created a new one, which is working with Sentry 8.x!

Have a look here: [mimischi/dokku-sentry](https://github.com/mimischi/dokku-sentry)
